tas:
  - name: Mark
  - name: Rachit
  - name: Yuntian

dates: ["", "Aug. 30", "Sep. 1", "Sep. 6", "Sep. 8", "Sep. 11", "Sep. 13", "Sep. 15", "Sep. 18","Sep. 20", "Sep. 22", "Sep. 25.", "Sep. 27.", "Sep. 29.", "Oct. 2", "Oct. 4", "Oct. 6", "Oct. 11", "Oct. 13", "Oct. 16", "Oct. 18", "Oct. 20", "Oct. 23", "Oct. 25", "Oct. 27", "Oct. 30", "Nov. 1","Nov. 3", "Nov. 6", "Nov. 8",  "Nov. 10", "Nov. 13", "Nov. 15","Nov. 17" , "Nov. 20", "Nov. 22", "Nov. 27", "Nov. 29", "Dec. 1"]
ohs:
  - time: Tue 8-10pm
    location: Quincy DH

lectures:
  - topic: <a>Advanced Machine Learning</a>
    subtopic:
    hw:
    papers:
    section:
    demos:
  - topic:
    subtopic:   <a href="https://github.com/harvard-ml-courses/cs181-section/blob/master/Section_0.pdf"> Math Review </a>
    hw:
    papers:
    section:
    demos:
    active: 'active'
  - topic: Fundamentals
    subtopic: Discrete Models
    hw: T0 <a href="https://harvard-ml-courses.github.io/cs181-s17-homeworks/h1/homework1-regression.pdf">Preliminary</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117075">submit</a> | <a href="https://canvas.harvard.edu/courses/21992/quizzes/54494">self-grading</a>)
    papers: 2.3, 3.5
    section:
    demos:
  - topic:
    subtopic:  Code Review
    hw:
    papers:
    section:
    demos:
    active: 'active'

  - topic:
    subtopic: Gaussian Models
    hw:
    papers: 2.4, 4.1, 4.3, 4.6
    section:
    demos:
  - topic:
    subtopic: Bayesian Models
    hw:
    papers: 3.3, 3.4
    section:
    demos:
  - topic:
    subtopic: Optimization
    hw:
    papers:
    section:
    demos:
    active: 'active'

  - topic:
    subtopic: Linear Regression and Classification
    hw: T1 <a href="https://harvard-ml-courses.github.io/cs181-s17-homeworks/h1/homework1-regression.pdf">Fundamentals</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117075">submit</a> | <a href="https://canvas.harvard.edu/courses/21992/quizzes/54494">self-grading</a>)
    papers: 7.3, 7.6
    section:
    demos:

  - topic: Graphical Models
    subtopic:  Directed Graphical Models
    hw:
    papers: 10.1, 10.2, 10.4
    section:
    demos:
  - topic:
    subtopic: Examples of Graphical Models
    hw:
    papers:
    section:
    demos:
    active: 'active'

  - topic:
    subtopic: GLMs and Markov Random Fields
    hw:
    papers: 9.1-3, 19.1-3
    section:
    demos:
  - topic: Exact Inference
    subtopic: Belief Propagation
    hw:
    papers: 20.1-3
    section:
    demos:
  - topic:
    subtopic: Graphical Models
    hw:
    papers:
    section:
    demos:
    active: 'active'
  - topic:
    subtopic:  Junction Tree Algorithms
    hw: T2 <a href="https://harvard-ml-courses.github.io/cs181-s17-homeworks/h2/homework2-classification.pdf">Models</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117078">submit</a> |  <a href="https://canvas.harvard.edu/courses/21992/quizzes/55050">self-grading</a> | <a href="https://canvas.harvard.edu/courses/21992/files/3662941/download?wrap=1">soln</a>)
    papers: 20.4
    section:
    demos:
  - topic: More Models
    subtopic:  Mixtures
    hw:
    papers: 11.1, 11.2, 11.4
    section:
    demos:
  - topic:
    subtopic: Exact Inference
    hw:
    papers:
    section:
    demos:
    active: 'active'
  - topic:
    subtopic: PCA and Factor Analysis
    hw:
    papers: 12.1, 12.2, 12.4
    section:
    demos:
  - topic:
    subtopic: Midterm Review
    hw:
    papers:
    section:
    demos:
    active: 'active'
  - topic:
    subtopic: Midterm
    hw:
    papers:
    section:
    demos:
  - topic: Variational Inference
    subtopic: Mean Field
    hw:
    papers: 21.1-21.3
    section:
    demos:
  - topic:
    subtopic: Review
    hw:
    papers:
    section:
    demos:
    active: 'active'
  - topic:
    subtopic: Advanced Variational Methods
    hw: T3 <a href="https://harvard-ml-courses.github.io/cs181-s17-homeworks/h2/homework2-classification.pdf">Inference</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117078">submit</a> |  <a href="https://canvas.harvard.edu/courses/21992/quizzes/55050">self-grading</a> | <a href="https://canvas.harvard.edu/courses/21992/files/3662941/download?wrap=1">soln</a>)
    papers: 22.1-3, 22.5
    section:
    demos:
  - topic:
    subtopic: MAP Estimation and LP Relaxations
    hw:
    papers: 21.6, 22.6
    section:
    demos:

  - topic:
    subtopic: Sampling
    hw:
    papers:
    section:
    demos:
    active: 'active'


  - topic: Sampling-Based Inference
    subtopic:   Monte Carlo Basics
    hw:
    papers: 2.7, 23.1-22.3
    section:
    demos:
  - topic:
    subtopic: Importance Sampling and Particle Filtering
    hw:
    papers: 23.4-23.5
    section:
    demos:
  - topic:
    subtopic: Practical MCMC
    hw:
    papers:
    section:
    demos:
    active: 'active'

  - topic:
    subtopic: Gibbs Sampling and MCMC
    hw:
    papers: 24.1-24.4
    section:
    demos:
  - topic: Time Series
    subtopic: Discrete Time Series
    hw:
    papers: 17.1-4
    section:
    demos:
  - topic:
    subtopic: Sampling
    hw:
    papers:
    section:
    demos:
    active: 'active'

  - topic:
    subtopic: Continuous Time Series
    hw: T4 <a href="https://github.com/harvard-ml-courses/cs181-s17-homeworks/tree/master/h5">Approximations</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117082">submit</a>)
    papers: 18.1-3
    section:
    demos:
  - topic: Deep Learning
    subtopic: Neural Networks
    hw:
    papers: 16.5
    section:
    demos:
  - topic:
    subtopic: Coding Neural Networks
    hw:
    papers:
    section:
    demos:
    active: 'active'

  - topic:
    subtopic: Convolutional and Recurrent Networks
    hw:
    papers: (Deep Learning Chapter)
    section:
    demos:
  - topic: DL Topics
    subtopic: Attention and Memory Models
    hw:
    papers: Attention, Memory Networks
    section:
    demos:
  - topic:
    subtopic: "Variational Autoencoders"
    hw:
    papers: VAE
    section:
    demos:
  - topic:
    subtopic: Applications
    hw:
    papers:
    section:
    demos:

  - topic:
    subtopic: Projects
    hw:
    papers:
    section:
    demos:
